name: flutter_string_encryption
description: Cross-platform string encryption using common best-practices.
version: 0.4.0

homepage: https://github.com/sroddy/flutter_string_encryption

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.github.sroddy.flutterstringencryption
        pluginClass: FlutterStringEncryptionPlugin
      ios:
        pluginClass: FlutterStringEncryptionPlugin
